version: "3.7"

services:
  nginx-php:
    image: webdevops/php-nginx-dev
    restart: "no"
    volumes:
      - ./src:/app
    ports:
      - "8080:80"

#   db:
#     image: mysql:5.7
#     environment:
#       MYSQL_DATABASE: wpdb
#       MYSQL_USER: wpuser
#       MYSQL_PASSWORD: wppass
#       MYSQL_RANDOM_ROOT_PASSWORD: "1"
#     volumes:
#       - ./db:/var/lib/mysql
#     restart: always

#   adminer:
#     depends_on:
#       - db
#     image: adminer
#     ports:
#       - "8088:8080"
#     restart: always

# volumes:
#   db:
